### ISSUE TITLE
catFR1 events broken

### ISSUE THREAD

**Issue by dunadan67** [pennmem/event_creation#13]
I think the last update that added TICL_CatFR events might've added a new bug to catFR1 event creation.  I get the following error when trying to generate new events for R1457T, catFR1, session_0, but also when testing on an old subject/session (R1444D, session 3) that formerly worked.

Traceback (most recent call last):
  File "event_creation/submission/automation.py", line 258, in run
    self.pipeline.run(force)
  File "event_creation/submission/pipelines.py", line 284, in run
    self._execute_tasks()
  File "event_creation/submission/pipelines.py", line 256, in _execute_tasks
    pipeline_task.run(transferred_files, self.destination)
  File "event_creation/submission/tasks.py", line 45, in run
    self._run(files, db_folder)
  File "event_creation/submission/events_tasks.py", line 261, in _run
    unaligned_events = parser.parse()
  File "event_creation/submission/parsers/hostpc_parsers.py", line 102, in parse
    return BaseLogParser.parse(self)
  File "event_creation/submission/parsers/base_log_parser.py", line 313, in parse
    events = self._empty_event
  File "event_creation/submission/parsers/base_log_parser.py", line 194, in _empty_event
    event = self.event_from_template(self._fields)
  File "event_creation/submission/parsers/base_log_parser.py", line 174, in event_from_template
    dtypes = cls.dtype_from_template(template)
  File "event_creation/submission/parsers/base_log_parser.py", line 184, in dtype_from_template
    dtypes = [(entry[0], entry[2], entry[3] if len(entry) > 3 else 1) for entry in template]
IndexError: tuple index out of range

**Comment by dunadan67** [comment]
I reset to a previous commit and catFR1 event creation worked, so it was definitely something in the last update on Thursday...

**Comment by dunadan67** [comment]
fix suggested by Leon.  Tested and works (so far).
